name: Publish Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # change if using .NET 8 or lower

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TelemedicineApp-windows
          path: publish/
